server:
  port: 9004

spring:
  application:
    name: user-service
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
